services:
  development:
    image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/brighton-frontend-web-frontend:dev
    container_name: brighton-dev
    ports:
      - "3000:3000"
    restart: on-failure
    env_file:
      - ./docker/development/.env
    mem_limit: 256m

  staging:
    image: $REGION-docker.pkg.dev/$PROJECT_ID/$REPO/brighton-frontend-web-frontend:staging
    container_name: brighton-staging
    ports:
      - "3001:3000"
    restart: on-failure
    env_file:
      - ./docker/production/.env
    mem_limit: 256m